# Generated by Django 4.1.3 on 2024-12-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='remember_expiry_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='warranty_status',
            field=models.CharField(choices=[('under_warranty', 'Under Warranty'), ('expired', 'Expired')], default='expired', max_length=50),
        ),
    ]
