# Generated by Django 4.1.3 on 2025-01-01 08:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fapp', '0006_alter_groupbalance_balance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupbalance',
            unique_together={('group', 'user')},
        ),
    ]
