# Generated by Django 4.1.3 on 2025-01-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0007_alter_groupbalance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupexpense',
            name='is_shared',
            field=models.IntegerField(choices=[(1, 'Shared'), (0, 'Individual')], default=1),
        ),
    ]
