# Generated by Django 4.1.3 on 2025-01-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0008_groupexpense_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupexpense',
            name='participating_members',
            field=models.ManyToManyField(blank=True, related_name='participating_expenses', to='fapp.groupmember'),
        ),
    ]
